language: php

php:
    - 5.4
    - 5.5

env:
    - HHVM=true
    - HHVM=false

before_install:
    - PHP_VERSION=`phpenv global`
    - if [[ "$HHVM" == true && "5.5" == "$PHP_VERSION" ]] ; then sudo bin/install_hhvm; export SCRIPT="hhvm --version"; fi
    - if [[ "$HHVM" == true && "5.5" != "$PHP_VERSION" ]] ; then export SCRIPT="exit"; fi
    - if [[ "$HHVM" == false ]] ; then export SCRIPT="php --version"; fi

script: "$SCRIPT"
